import React, { useState } from 'react';
import type { Incident } from '../../types/incident';
import { FileText, Copy, Check, Download, X } from 'lucide-react';

interface ExportReportModalProps {
  incident: Incident;
  onClose: () => void;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({ incident, onClose }) => {
  const [copied, setCopied] = useState<boolean>(false);

  const markdownContent = `# OpsRelay Shift Handoff & Incident Report: ${incident.id}

**Title:** ${incident.title}  
**Severity:** ${incident.severity} | **Status:** ${incident.status}  
**Impacted Service:** \`${incident.service}\` (${incident.component})  
**Lead SRE:** ${incident.leadSRE}  
**Created At:** ${incident.createdAt}  
${incident.resolvedAt ? `**Resolved At:** ${incident.resolvedAt} (MTTR: ${incident.mttrMinutes} mins)` : '**Status:** Active Investigation'}

---

## Executive Summary
${incident.summary}

---

## Incident Timeline
${incident.timeline.map(t => `- **[${t.timestamp}] (${t.actor})** ${t.title}: ${t.description}`).join('\n')}

---

## Decisions Logged
${incident.decisions.map(d => `- **${d.title}** (by ${d.madeBy}): ${d.description} *[Impact: ${d.impact}]*`).join('\n')}

---

## Mitigations & Fixes Applied
${incident.fixesApplied.map(f => `- [x] ${f}`).join('\n')}

---

## Action Items & Tasks
${incident.tasks.map(t => `- [${t.status === 'COMPLETED' ? 'x' : ' '}] **[${t.priority}]** ${t.title} (Assignee: ${t.assignee})`).join('\n')}

---
*Generated by OpsRelay AI Incident Response Agent*
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement('a');
    const file = new Blob([markdownContent], { type: 'text/markdown' });
    element.href = URL.createObjectURL(file);
    element.download = `${incident.id}-handoff-report.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fadeIn">
      <div className="w-full max-w-3xl rounded-xl border border-cockroach-red/40 bg-ops-card p-6 shadow-glow-red space-y-4 max-h-[90vh] flex flex-col">
        <div className="flex items-center justify-between border-b border-ops-border pb-3">
          <div className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-cockroach-red" />
            <h3 className="font-mono text-base font-bold text-white">
              Export Handoff Report: {incident.id}
            </h3>
          </div>
          <button onClick={onClose} className="p-1 text-ops-muted hover:text-white rounded">
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto bg-ops-bg rounded-lg p-4 font-mono text-xs text-ops-text border border-ops-border leading-relaxed whitespace-pre-wrap">
          {markdownContent}
        </div>

        <div className="flex items-center justify-between pt-2 border-t border-ops-border">
          <span className="text-xs font-mono text-ops-subtext">Formatted in Markdown</span>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 rounded bg-ops-sidebar hover:bg-ops-border border border-ops-border px-3 py-1.5 font-mono text-xs text-white transition-colors"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
              {copied ? 'Copied Markdown' : 'Copy Markdown'}
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 rounded bg-cockroach-red hover:bg-cockroach-redHover px-4 py-1.5 font-mono text-xs font-bold text-white shadow-glow-red-sm transition-all"
            >
              <Download className="h-3.5 w-3.5" /> Download .md File
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
