import React, { useState } from 'react';
import type { Incident } from '../../types/incident';
import { FileText, Copy, Check, DownloadSimple, X } from '@phosphor-icons/react';

interface ExportReportModalProps {
  incident: Incident;
  onClose: () => void;
}

function buildNextSteps(incident: Incident): string[] {
  const openTasks = incident.tasks.filter((t) => t.status !== 'COMPLETED');
  const steps = openTasks.slice(0, 4).map((t) => `${t.title} (${t.priority}, ${t.assignee})`);
  if (incident.status !== 'RESOLVED') {
    steps.unshift(`Confirm ${incident.service} health metrics and error rate before shift handoff`);
  }
  if (steps.length === 0) {
    steps.push('Schedule post-incident review and document lessons learned');
  }
  return steps;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({ incident, onClose }) => {
  const [copied, setCopied] = useState(false);
  const nextSteps = buildNextSteps(incident);

  const markdownContent = `# OpsRelay Shift Handoff & Incident Report: ${incident.id}

**Title:** ${incident.title}  
**Severity:** ${incident.severity} | **Status:** ${incident.status}  
**Impacted Service:** \`${incident.service}\` (${incident.component})  
**Lead SRE:** ${incident.leadSRE}  
**Created At:** ${incident.createdAt}  
${incident.resolvedAt ? `**Resolved At:** ${incident.resolvedAt} (MTTR: ${incident.mttrMinutes} mins)` : '**Status:** Active investigation'}

---

## Executive Summary
${incident.summary}

---

## Incident Timeline
${incident.timeline.length > 0
    ? incident.timeline.map((t) => `- **[${t.timestamp}] (${t.actor})** ${t.title}: ${t.description}`).join('\n')
    : '_No timeline events recorded._'}

---

## Decisions Logged
${incident.decisions.length > 0
    ? incident.decisions.map((d) => `- **${d.title}**${d.madeBy ? ` (by ${d.madeBy})` : ''}: ${d.description}${d.impact ? ` *[Impact: ${d.impact}]*` : ''}`).join('\n')
    : '_No decisions logged._'}

---

## Mitigations & Fixes Applied
${incident.fixesApplied.length > 0
    ? incident.fixesApplied.map((f) => `- [x] ${f}`).join('\n')
    : '_No fixes applied yet._'}

---

## Action Items & Tasks
${incident.tasks.length > 0
    ? incident.tasks.map((t) => `- [${t.status === 'COMPLETED' ? 'x' : ' '}] **[${t.priority}]** ${t.title} (Assignee: ${t.assignee})`).join('\n')
    : '_No tasks assigned._'}

---

## Next Steps (Shift Handoff)
${nextSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

---

## Architecture Notes
- **Amazon Bedrock** — Haiku extraction + Nova agent reasoning for structured incident drafts
- **CockroachDB Distributed Vector Indexing** — Titan 1,024-d embeddings with cosine similarity for Ask AI memory
- **CockroachDB Cloud Managed MCP** — read-only approved evidence citations for investigator queries

---
*Generated by OpsRelay AI Incident Response Agent*
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement('a');
    const file = new Blob([markdownContent], { type: 'text/markdown' });
    element.href = URL.createObjectURL(file);
    element.download = `${incident.id}-handoff-report.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm">
      <div className="w-full max-w-3xl rounded-xl border border-ops-border bg-white p-6 shadow-xl space-y-4 max-h-[90vh] flex flex-col">
        <div className="flex items-center justify-between border-b border-ops-border pb-3">
          <div className="flex items-center gap-2">
            <FileText size={20} weight="regular" className="text-brand" aria-hidden />
            <h3 className="text-base font-semibold text-ops-text">
              Handoff Report: {incident.id}
            </h3>
          </div>
          <button type="button" onClick={onClose} className="rounded-lg p-1 text-ops-muted hover:text-ops-text">
            <X size={20} weight="regular" aria-hidden />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto rounded-lg border border-ops-border bg-slate-50 p-4 font-mono text-xs text-ops-subtext leading-relaxed whitespace-pre-wrap">
          {markdownContent}
        </div>

        <div className="flex items-center justify-between pt-2 border-t border-ops-border">
          <span className="text-xs text-ops-muted">Markdown · includes tasks, timeline, and architecture notes</span>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopy}
              className="ops-btn-secondary text-xs min-h-[36px]"
            >
              {copied ? <Check size={14} weight="regular" className="text-emerald-600" aria-hidden /> : <Copy size={14} weight="regular" aria-hidden />}
              {copied ? 'Copied' : 'Copy'}
            </button>
            <button
              type="button"
              onClick={handleDownload}
              className="ops-btn-primary text-xs min-h-[36px]"
            >
              <DownloadSimple size={14} weight="regular" aria-hidden /> Download .md
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
